version: '3'
services:
  orchestration:
    container_name: orchestration
    build:
      context: ./orchestration
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  input:
    container_name: input
    build:
      context: ./input
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ORCHESTRATION_URL=http://orchestration:8080/
    depends_on:
      - orchestration

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"