scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'orchestration'
    scrape_interval: 5s
    static_configs:
      - targets: ['orchestration:8080']
